### ISSUE TITLE
Autostart top of Queue Torrents

### ISSUE THREAD

**Issue by forsomefun2** [dchang0/torrentwatch-xa#11]
Is it possible to make very torrent go to the top of the queue and autostart from torrentwatch

**Comment by dchang0** [comment]
Could you elaborate further? I don't know what you mean by:

1) Every torrent--do you mean every torrent in the All list? Or every torrent in Favorites? Or every torrent in the Transmission list?

2) Top of the queue--I don't know what you mean by queue.

**Comment by forsomefun2** [comment]
So I think the program is adding torrents from my favorites list to transmission to the transmission download queue.
I think before they were autostarting 
but now they are in the transmission queue waiting to download

**Comment by dchang0** [comment]
Oh, okay. That is normal behavior and is entirely due to Transmission. torrentwatch-xa merely submits the item to the Transmission daemon; it submits every item asking Transmission to autostart it. Transmission decides which torrents and how many to actually download.
You can tweak settings in Transmission to get it to download more items simultaneously until it maxes out your bandwidth. And you can change the priority of torrents to change the order in which they are downloaded, although this feature also depends on bandwidth and circumstances.

**Comment by dchang0** [comment]
I found documentation on the Transmission daemon's settings.json file here:

https://github.com/transmission/transmission/wiki/Editing-Configuration-Files

The settings you will want to tweak is:
download-queue-enabled
download-queue-size

The default is true for the former and 5 for the latter.
