### ISSUE TITLE
Torrentwatch-xa feed list not syncronized with feed source

### ISSUE THREAD

**Issue by JohnDarkhorse** [dchang0/torrentwatch-xa#16]
In theory, every 15 minutes Torrentwatch-xa should pull the latest RSS feed from the source.

In theory, should I visit the website of the source, the available items listed there should match within ±15 minutes of what Torrentwatch-xa is showing as available.

My Torrentwatch-xa is regularly out of this sync range (again, deleting the feed cache brings everything back into sync), sometimes for more than an hour.

&nbsp;

So, either TW-XA isn't pulling the feeds every 15 minutes or it's pulling them but not parsing them.

**Comment by dchang0** [comment]
I'm pretty sure this is related to the other issue you have (#14).
At this point, I suspect there's a problem with the cron job or the cron daemon.
We'll have to do some more diagnostics, especially since #14 seems to be resolved, yet it isn't working 100%.

Here is one diagnostic test you should try.

We know that when you clear the feed cache in the web UI, it then gets the RSS feed(s) and parses them successfully. But that's the web UI doing the pulling of the feeds, not the cron job.

So, the test to do is to close the web UI, ssh into the server, and run these commands to manually clear the feeds:

```
cd /var/lib/torrentwatch-xa/dl_cache
sudo rm rsscache_*

```
Wait for the cron job to run and see what happens. I expect this to fail even though there are no cache files in /var/lib/torrentwatch-xa/dl_cache

Check the system log, twxalog, and also the permissions and owner:group of the folder:

`ls -ld /var/lib/torrentwatch-xa/dl_cache`

We've done this before in #14, but we gotta do this again to make sure.

**Comment by JohnDarkhorse** [comment]
`drwxr-xr-x 2 www-data www-data 4096 May 20 18:30 /var/lib/torrentwatch-xa/dl_cache/`

rsscache_* files are being written every 15 minutes (I have two feeds, so two rsscache* files)

twxalog shows a series of these every 15 minutes: `2021-05-20T18:00:04-05:00 ERR: RPC error in auto-delete:`

**Comment by dchang0** [comment]
Well, that's good news that the rsscache_* files are being written.

Keeping the web UI closed and only allowing the cron job to run, could you watch the size of the rsscache_* files and make sure they keep changing?

It might help to check their contents too, looking to see if they match up to the RSS feeds in terms of items. They are text files. You can open them and look for the timestamps and get some idea if they're really updating. If they are, then they are parsing the feeds properly.

As for the RPC error in auto-delete, that means that the cron job is having trouble talking to the transmission-daemon to perform the auto-delete of torrents that have reached the seed ratio and are no longer seeding. I'll look into that.

**Comment by dchang0** [comment]
BTW, the web UI for torrentwatch-xa does not auto-refresh in the browser every 15 minutes.
The cron job runs and updates the feed caches and does its auto-downloads and auto-deletes, but it cannot tell the web browser to auto-refresh.

If you want the browser to auto-refresh every x minutes, that is a feature that has not been written yet. It would be done in Javascript on the browser side. It's something I've thought about but haven't seen a need for yet.

**Comment by JohnDarkhorse** [comment]
> It might help to check their contents too, looking to see if they match up to the RSS feeds in terms of items. They are text files. You can open them and look for the timestamps and get some idea if they're really updating.

rsscache* files are being rewritten every 15 minutes (while I'm watching) with up-to-date timestamps

> As for the RPC error in auto-delete, that means that the cron job is having trouble talking to the transmission-daemon

To be expected, as I'm not running Transmission (the TWXA is set to deposit the torrent files into a watch directory)

> BTW, the web UI for torrentwatch-xa does not auto-refresh in the browser every 15 minutes.

Yes, I'm aware of that, and it is not what I'm describing.

I have a browser tab sleep thing that puts unused browser tabs "to sleep" after so many minutes, and they reload upon "waking".

**Comment by dchang0** [comment]
For the RPC error, if you are not running Transmission, just turn off the auto-delete feature under Configure > Torrent > Auto-Del Seeded Torrents.
---
Okay, back to the original issue.

This is particularly difficult to diagnose because we don't have any kind of log of the RSS feed. The cache files are not easy to watch with the `tail -f` command.

So, here's the general process to diagnosing the problem.

1) At any given point in time, check the web UI and look at the RSS feed in torrentwatch-xa, then check the original RSS Feed from the source website.

2) If they are different, immediately open the rsscache_ file and look at the timestamp of the last few items (near the top of the file).

3) Cross-reference the items you see there at the end of the rsscache_ file to the web UI (they should match) and the original RSS feed (the cache should be a few items behind the original RSS feed--basically everything since the last time the cron job ran will not show up in the cache).

---

I'll give you an example.

Right now my web UI's last item is "Sootery Shadows House - 06 1080p May 20 18:35"
The last item in the cache file is "[Sootery] Shadows House - 06 [1080p][988902E2]" published "2021-05-20T18:35:10-07:00"
That matches the web UI.

Then, I visited the live RSS feed on the source website (animetosho.org) and the last item is also "[Sootery] Shadows House - 06 [1080p][988902E2]" published "01:35" (different timezone).

They all match in my feed.

Now, out of your situation, which one or two are out of sync with the others? I expect that your web UI matches your rsscache_ but that they are both behind the live RSS feed...

If so, how far do they lag? They can lag up to 15 minutes at most due to the cron job being scheduled every 15 minutes.

**Comment by JohnDarkhorse** [comment]
What happens when the source URL is unreachable?

**Comment by dchang0** [comment]
If the source URL is unreachable, the feed will be hidden from view in the web UI (its title will be shown in red, and none of its items will be displayed).
In the background, the cron job will keep contacting the source URL every 15 minutes, and when it succeeds, it will finally pull down the items and make a new cache file. Obviously it will fail to auto-download anything since it cannot read the RSS feed from the source.

**Comment by dchang0** [comment]
Okay, I've dug into the code, and I think this may be normal behavior.
This section of code in twxa_feed.php (that came from TorrentWatch-X) involves a Cache Time setting that prevents the cache from updating too frequently.

```
function parse_one_rss($feed, $update = null) {
    global $config_values;
    $rss = new lastRSS;
    $rss->stripHTML = true;
    $rss->CDATA = 'content';
    if ((isset($config_values['Settings']['Cache Time'])) && ((int) $config_values['Settings']['Cache Time'])) {
        $rss->cache_time = (int) $config_values['Settings']['Cache Time'];
    } else if (!isset($update)) {
        $rss->cache_time = 86400;
    } else {
        $rss->cache_time = (15 * 60) - 20;
    }

```

The cache time logic is in the file twxa_lastRSS.php (also carried over from TorrentWatch-X):

```
function Get($rss_url) {
        // If CACHE ENABLED
        if ($this->cache_dir != '') {
            $cache_file = $this->cache_dir . '/rsscache_' . md5($rss_url);
            // Changed to only support local files
            $timedif = @(time() - filemtime($cache_file));
            if ($timedif < $this->cache_time) {
                writeToLog("Feed loaded from file cache: $rss_url\n", 2);
                // cached file is fresh enough, return cached array
                $result = unserialize(join('', file($cache_file)));
                // set 'cached' to 1 only if cached file is correct
                if ($result) {
                    $result['cached'] = 1;
                }
            } else {
                writeToLog("Feed cache is old, loading fresh: $rss_url\n", 2);
                // cached file is too old, create new
                $result = $this->Parse($rss_url);
                if ($result['items_count'] >= 0) {
                    $serialized = serialize($result);
                    if ($f = @fopen($cache_file, 'w')) {
                        fwrite($f, $serialized, strlen($serialized));
                        fclose($f);
                    }
                    if ($result) {
                        $result['cached'] = 0;
                    }
                }
            }
        }
        // If CACHE DISABLED >> load and parse the file directly
        else {
            $result = $this->Parse($rss_url);
            if ($result) {
                $result['cached'] = 0;
            }
        }
        // return result
        return $result;
    }
```

So, there might be three easy ways for you to fix this:

1) Disable the cache. Apparently, this will force torrentwatch-xa to load the RSS feed every single time it runs. This could be bad for bandwidth and will certainly slow down the web UI.

2) Manually insert a setting into the config file called "Cache Time" and set it really low, like just under (15 * 60) - 20 = 880 seconds. This effectively forces the cron job to load the RSS feed every time it runs, but the web UI will enjoy just under 15 minutes of caching. Notice that this line does exactly (15 x 60) - 20 seconds:

`$rss->cache_time = (15 * 60) - 20;`

3) Without inserting a Cache Time setting into the config file, change this line:

`$rss->cache_time = 86400;`

to 

`$rss->cache_time = 880;`

Let me know which of these methods you chose/tried and how it works out.

**Comment by JohnDarkhorse** [comment]
(I've not implemented any of the latest suggestions - this is just a note)

Here is what I think is happening:

The RSS source only provides 50 listings at a time in their RSS feed.

If TWXA checks every 15 minutes (by cron), but ignores half a day's worth because the cache isn't old enough, that's a lot of missed shows (and really doesn't make much sense to me, at all)

Depending on the day of the week and the time of day, missing just an hour's worth of RSS feeds can cause shows to be missed.

**Comment by dchang0** [comment]
Thanks for the note.
If you don't mind, could you tell me the RSS feed URL? I could test it myself and figure out a workaround.

You're correct--it's a very bad thing if the cache age causes missed shows. I'll probably have to rewrite the cache calculations entirely. Or, more likely, I'll remove any cache time/age setting entirely or make it very small, like 5 minutes.

**Comment by JohnDarkhorse** [comment]
> BTW, option 2 with Cache Time is probably your easiest/best choice. You don't have to get into the source code and can simply add an entry to the Settings section in the config file.

I don't grok whatever format the config file is in, and have no clue how to implement that.

Throwing it in at the bottom of the config as you posted it breaks TWXA.


It seems the simplest answer to both my issues here would be `14 * * * * /usr/bin/rm /path/to/rsscache_*

For me, the Web UI doesn't have to update in picoseconds, so long as it updates once every 15 minutes, and - after the "favorites list" is set up, the web UI won't be needed at all.


Thanks for your patience :)

**Comment by dchang0** [comment]
That's a really clever solution you came up with--nice!

I recommend a slight change to the cron job line:

`14,29,44,59 * * * * /usr/bin/rm /path/to/rsscache_*`

You want to catch it just before the 0,15,30,45 minute for the twxa_cli.php run.

I do plan on removing/fixing/simplifying the cache time logic in the next major version thanks to your reporting this issue.

**Comment by dchang0** [comment]
BTW, I just pushed a patch to 1.5.0 to always disable auto-del if Client = Save Torrent In Folder so that you don't get those annoying RPC errors.

I have discovered another bug affecting people who use Client = Save Torrent In Folder where it generates harmless "ERR: No torrent hash in cache file" errors and will fix that next.

**Comment by dchang0** [comment]
FYI, probably in version 1.7.0, I will add the ability to set the cache expiry per feed so that some feeds can be set to cache for 24 hours while other feeds can be set to cache just under 15 minutes (every run forces a refresh of the feed).

Version 1.6.0 is reserved for the switch to PicoFeed for parsing RSS feeds, a major change that will require extensive testing. So version 1.7.0 will likely be a long while from now. It is possible but unlikely that I will add the cache expiry in version 1.6.0.

**Comment by dchang0** [comment]
Sorry to bother you even after the issue is closed.
While studying the cache expiration logic for the proposed improvement, I have found that under normal circumstances, the feed cache is supposed to refresh every 14 minutes and 50 seconds on its own for all feeds.
Thus, your situation is still unique and probably involves some kind of bug or permissions problem.
A workaround should not be necessary, even for a feed that requires a refresh every 15 minutes.
I may not add the proprosed improvement after all, since the logic cloned from TorrentWatch-X already refreshes the feed cache every 14 minutes and 50 seconds by design. Instead, I'll focus on QA to make sure it works as intended.

**Comment by JohnDarkhorse** [comment]
Hello Margaret, it's me again . . .

Got a couple of wee requests:

> There are third-party tools that easily convert magnet links stored in text files to torrent files, if you prefer the torrent file over the magnet link.

Can you link to some examples?  I've seen magnet-to-torrent converters that take the infohash & query a torrent repository for the matching file and those that take an infohash & produce a rudimentary torrent file, but I've never heard of any that parse a text file for the infohash to produce a torrent file.

&nbsp;

. . .and could you provide some one-liner examples of how one would fill the fields using "simple", "glob" and "regexp" methods?

(apologies, I am dense at this sort of thing)

**Comment by dchang0** [comment]
Re: third-party tools that convert magnet links to torrent files:

You are correct--the tools I refer to are all online tools. They cannot 
parse the magnet links into torrent files with only the magnet link.  
AFAIK, it is not possible to do so without some kind of access to the 
internet. The converters you have seen are almost certainly the same 
ones I am referring to, such as:

http://magnet2torrent.com
BitTorrent Info Hash (BTIH) to Magnet URI converter (daniel.priv.no) 
<https://www.daniel.priv.no/tools/btih-to-magnet/>

Re: examples of simple, glob, regexp:

simple (literal, no wildcards) matching:

To match a title, you must spell out a complete substring (case 
insensitive) found within the title.

Gloomy

The above line will match ANY title that has the word "gloomy" in it.

glob (filename style) matching:

You can use simple filename style wildcards. Most people use the * 
asterisk wildcard. Why use this method and not simple above? Because you 
can now do this:

Vivy*Song

The above line will match "Vivy: Fluorite Eye's Song"

Simple can't do the asterisk in the middle.

Simple is the same as

*keyword*

In glob mode. So, glob provides a minor advantage in that you can use 
wildcards in a slightly more advanced way.

One advantage of glob method is that you can do this:

gr[ea]y

will match any title with either "gray" or "grey" in it. Simple would 
not be able to do this.

regexp (Perl-compatible Regular Expression) matching:

RegExp matching is very different from simple or glob.

I can't explain all the things it can do here because it is so powerful, 
but I'll give you an example:

Let's say you want the show "Berserk" from any of three specific 
fansubbing crews that you trust: Erai-raws, Subsplease, and SSA. But you 
don't want it from any other fansubbing crews.

So you could write:

(Erai-raws|Subsplease|SSA) Berserk

That would only get these titles:

Erai-raws Berserk
Subsplease Berserk
SSA Berserk


I like to use RegExp to match resolutions/qualities. For instance, I 
don't like 1080p (too large) so I usually set up my Qualities line as:

(720p|480p)

This will get only the 720p or 480p versions of a Favorite, whichever 
comes first.

Hope that helps.

BTW, version 1.6.0 has the "cache expires in ### seconds" in the twxalog 
if in DEBUG mode, so you can figure out what's going on with your cache 
expirations better.





------ Original Message ------
From: "JohnDarkhorse" ***@***.***>
To: "dchang0/torrentwatch-xa" ***@***.***>
Cc: "dchang0" ***@***.***>; "Comment" 
***@***.***>
Sent: 6/28/2021 09:27:17
Subject: Re: [dchang0/torrentwatch-xa] Torrentwatch-xa feed list not 
syncronized with feed source (#16)

**Comment by JohnDarkhorse** [comment]
> Explanations

Thanks for the explanations (maybe put them in the usage.md? hint hint)  The more you make this easy for the less-nerdy, the more adoption you'll see.

I mean, some folks have no issues installing code as directed, but "glob" & "regexp" may throw them for a loop (\*cough\* looks in mirror \*cough\*)

&nbsp;

I just installed (per instructions) today's version of the code and am not using the "nuke the cache every quarter hour" option previously discussed.  The software appears to be performing as advertised (not like before, where all the hair pulling & swearing and nuclear options were needed) as far as staying up to date & in sync with the torrent source website.

I will need to go through and rewrite all my favorites, as I'd no clue on the first go-round.

**Comment by dchang0** [comment]
That's great news--glad to hear that the latest version works properly 
for you!

And that's a great idea--I will definitely include the explanations in 
the USAGE.md. I need to improve the examples a bit to include some edge 
cases that show the differences better.


------ Original Message ------
From: "JohnDarkhorse" ***@***.***>
To: "dchang0/torrentwatch-xa" ***@***.***>
Cc: "dchang0" ***@***.***>; "Comment" 
***@***.***>
Sent: 6/28/2021 13:40:20
Subject: Re: [dchang0/torrentwatch-xa] Torrentwatch-xa feed list not 
syncronized with feed source (#16)

**Comment by dchang0** [comment]
USAGE.md has just been updated with more documentation on Simple vs. Glob vs. RegExp.

They cover enough examples to show the main differences between the three.

Thanks for the tips and feedback!
