### ISSUE TITLE
Some ignored favorite batch torrents are displayed as "Previously Downloaded"

### ISSUE THREAD

**Issue by efelon** [dchang0/torrentwatch-xa#7]
Hi dchan0,

as you wished i opened an issues for this, although the behavior changed from the description in the other issue #4. Precondition was also that i manually emptied dl_cache directory after first open the installation in the browser, then emptied the browser cache.

OS: Linux Mint 18.3 64-bit
Browser: Chromium (Version 66.0.3359.181 (Official Build))
torrenwatch-xa 1.1.0 (from master)

* All "2xFULL" of the batches are now shown as ignored.
* One still shows as the title says. Difference for this one is that it is matched as "2x2018". Debug level log:
> 2018-07-08T08:47:59+02:00 ERR: No torrent hash in cache file: /var/lib/torrentwatch-xa/dl_cache/dl_westworld s02 2018 solod rus webdlrip
> 2018-07-08T08:47:59+02:00 INF: Equiv. in cache; ignoring: westworld s02 2018 solod rus webdlrip

A "dl_" file is also created in the dl_cache directory.

Also one thing i noticed is, that after pressing "clear cache All" and watching the dl_cache directory. It deletes all files (except README) and rebuilds the caches immediately. After the process is finished the "Clear Cache" dialog still remains open. Shouldn't it close when it's finished?

Greetings

**Comment by dchang0** [comment]
Re: "All "2xFULL" now ignored"
I'll close the other issue. Thanks for confirming that it worked.

Re: "2x2018"
That is a pattern-matching problem caused by the torrent creator's unusual naming style. It might not be fixable in that it will probably involve a trade-off with a different pattern. You could block it using the Episode filter in the Favorite (use regular expressions) like so:

2x1-2x99

This will get all Season 2 episodes from Episode 1 to Episode 99. This guy's fake 2x2018 full season will get blocked because it looks like Season 2, Episode 2018, and 2018 > 99.

Re: "A "dl_" file is also created..."
Yeah, that would happen since it matched and downloaded. That is normal. After blocking the item using the Episode filter, you can delete the dl_ file for it.

Re: Clear Cache > All rebuilds caches immediately
That's normal also. The RSS feed caches rebuild right away no matter what. The Torrent caches (those files that begin with dl_) and the History file (dl_history) are destroyed and not recreated. The next download will of course create its own dl_ file, though it will probably not be the same as the ones that were destroyed.

Re: Clear Cache dialog remains open
I figure some people may want to first clear Torrents, then Feeds, then All, in that order, to try to get things to work from least-forceful to most, but your suggestion is a good one. I may implement it in the future.

**Comment by efelon** [comment]
I get it. Thanks for the explanation. But as long as it is not downloading this false matches I'm fine with them being displayed that way.

**Comment by dchang0** [comment]
Give the Episode filter a try and close the ticket after confirming that it blocks the 2x2018 fake. Thanks!

**Comment by efelon** [comment]
With the following setting:

![image](https://user-images.githubusercontent.com/10722552/42497534-f8ffac86-8429-11e8-8b52-ad469b825098.png)

it does show them all as "Not a Match". So this "Episode" line in the favorites is meant as exclusion filters? 

Other than that you can close this.

**Comment by dchang0** [comment]
Technically the Episodes filter is an inclusion filter, but in your case you are using it to intentionally exclude 2x2018. (Can't include some items in a category without simultaneously excluding other items.)

Thanks for reporting back.

**Comment by efelon** [comment]
You're welcome.

Btw. with the episode filter it also ignores all the batches regardless of the setting to ignore batches.

**Comment by dchang0** [comment]
I guess I need to widen the textbox for Seed Ratio, based on the screenshot. Thanks for sending that. It will be tougher to do, though, because Last Downloaded needs a lot of room for dates.

**Comment by dchang0** [comment]
Re: "Btw. with the episode filter it also ignores all the batches regardless of the setting to ignore batches."

Interesting. It's not supposed to do that. I will see if I can fix that easily. You've been a huge help reporting all the bugs--thanks!
